# Generated by Django 6.0.6 on 2026-07-04 17:05

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default='Институция', max_length=100)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, default='<p>История, документы и совет фонда «АРТ-Кавказ» — открытость и надёжность для партнёров, государственных структур и творческих сообществ.</p>')),
                ('og_image', models.ForeignKey(blank=True, help_text='Изображение для соцсетей (Open Graph, рекомендуется 1200×630). Если не указано — используется изображение по умолчанию из настроек сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Раздел «О фонде»',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CouncilPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Изображение для соцсетей (Open Graph, рекомендуется 1200×630). Если не указано — используется изображение по умолчанию из настроек сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Совет фонда',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(help_text='Например: Президент фонда', max_length=200)),
                ('role_subtitle', models.CharField(blank=True, help_text='Например: Архитектор', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='about.councilpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('og_image', models.ForeignKey(blank=True, help_text='Изображение для соцсетей (Open Graph, рекомендуется 1200×630). Если не указано — используется изображение по умолчанию из настроек сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Документы фонда',
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('file_type_label', models.CharField(choices=[('PDF', 'PDF'), ('JPEG', 'JPEG'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX')], default='PDF', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('size_note', models.CharField(blank=True, help_text='Например: 1.4 МБ', max_length=30)),
                ('action_label', models.CharField(choices=[('download', 'Скачать ↓'), ('view', 'Просмотр ↗')], default='download', max_length=20)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='about.documentspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('timeline', wagtail.fields.StreamField([('entry', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 10}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('core.blocks.APIImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('year', 0), ('title', 1), ('description', 2), ('image', 3)]], {})})),
                ('og_image', models.ForeignKey(blank=True, help_text='Изображение для соцсетей (Open Graph, рекомендуется 1200×630). Если не указано — используется изображение по умолчанию из настроек сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'История фонда',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
