# Generated by Django 6.0.6 on 2026-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerspage',
            name='cta_button_link',
            field=models.CharField(blank=True, help_text='Например: mailto:info@artkavkaz.ru', max_length=255),
        ),
    ]
