# Generated by Django 6.0.6 on 2026-07-04 17:05

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='eyebrow',
            field=models.CharField(default='Институция', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('core.blocks.APIImageChooserBlock', (), {'help_text': 'Фоновое изображение баннера (плейсхолдер, если не задано)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Куда ведёт кнопка баннера', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('button_text', 3), ('button_page', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_heading',
            field=models.CharField(default='О фонде', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_quote',
            field=models.CharField(blank=True, default='Сохранение, развитие и популяризация культуры, искусства и архитектуры Кавказа.', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, default='<p>«АРТ-Кавказ» — некоммерческий фонд, работающий на стыке искусства, архитектуры и культурного наследия. Мы поддерживаем художников и архитекторов, организуем выставки и формируем устойчивый диалог между регионами Кавказа и международным культурным сообществом.</p>'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_eyebrow',
            field=models.CharField(default='Зачем мы работаем', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_heading',
            field=models.CharField(default='Миссия фонда', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_text',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Мы сохраняем и переосмысляем культурное наследие Кавказа, поддерживаем художников и архитекторов и выстраиваем устойчивый диалог между традицией и современностью.</p>'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Изображение для соцсетей (Open Graph, рекомендуется 1200×630). Если не указано — используется изображение по умолчанию из настроек сайта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats',
            field=wagtail.fields.StreamField([('stat', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: 12 или 150+', 'max_length': 20}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Лет работы фонда', 'max_length': 100}), 2: ('wagtail.blocks.StructBlock', [[('value', 0), ('label', 1)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_eyebrow',
            field=models.CharField(default='Фонд в цифрах', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_heading',
            field=models.CharField(default='12 лет культурной работы на Кавказе', max_length=200),
        ),
    ]
