# Generated by Django 6.0.6 on 2026-07-04 17:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_eyebrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 5)], blank=True, block_lookup={0: ('core.blocks.APIImageChooserBlock', (), {'help_text': 'Фоновое изображение баннера (плейсхолдер, если не задано)', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 4: ('core.blocks.APIPageChooserBlock', (), {'help_text': 'Куда ведёт кнопка баннера', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('button_text', 3), ('button_page', 4)]], {})}),
        ),
    ]
