# Generated by Django 6.0.6 on 2026-07-04 17:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 6)], blank=True, block_lookup={0: ('core.blocks.APIImageChooserBlock', (), {'help_text': 'Фоновое изображение баннера (плейсхолдер, если не задано)', 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Светлый (тёмный текст)'), ('dark', 'Тёмный (белый текст)')], 'help_text': 'Определяет контраст текста и элементов управления слайдера поверх изображения'}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 5: ('core.blocks.APIPageChooserBlock', (), {'help_text': 'Куда ведёт кнопка баннера', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('theme', 1), ('title', 2), ('description', 3), ('button_text', 4), ('button_page', 5)]], {})}),
        ),
    ]
