# Generated by Django 6.0.6 on 2026-07-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (8672) 40-00-00', max_length=32)),
                ('city', models.CharField(default='Владикавказ', max_length=100)),
                ('region', models.CharField(default='РСО-Алания', max_length=100)),
                ('address', models.CharField(default='г. Владикавказ, РСО-Алания', max_length=255)),
                ('email', models.EmailField(default='info@artkavkaz.ru', max_length=254)),
                ('org_legal_name', models.CharField(default='Некоммерческий фонд «АРТ-Кавказ»', max_length=255)),
                ('footer_description', models.TextField(default='Некоммерческий фонд поддержки культуры, искусства и архитектуры. Сохранение и развитие наследия Кавказа.')),
                ('telegram_url', models.URLField(blank=True)),
                ('vk_url', models.URLField(blank=True)),
                ('max_messenger_url', models.URLField(blank=True, help_text='Ссылка на канал в мессенджере "Макс"')),
                ('rutube_url', models.URLField(blank=True)),
                ('default_og_image', models.ForeignKey(blank=True, help_text='Используется, если у страницы не задано своё og_image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
    ]
